apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transformer-code
spec:
  # ReadWriteOnce means the volume can be mounted as read-write by a single pod.
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi