defaults:
  - model: transformer
  - data: fields
  - model: transformer
  - data: fields
  - trainer: default
  - _self_

hydra:
  run:
    dir: ${paths.results}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# --- Global Project Configuration ---
project_name: "fields-transformer"
mode: resume
mlflow_run_id: 8b208eeae0d1427b9b4ae2d7461b9d39
version: "1.0.0"
matmul_precision: "medium"

# --- Single Source of Truth: paths ---
paths:
  # absolute path for project root
  project_root: ${hydra:runtime.cwd}
  # root output directory for all runs
  results: "${paths.project_root}/results/transformer"
  nf_data: "${paths.project_root}/data/dataset_155.pt"
  ir_data: "${paths.project_root}/data/IR_v09_df_all_features.parquet"
  ckpt: "${paths.results}/mlruns/713624924803142620/8b208eeae0d1427b9b4ae2d7461b9d39/artifacts/checkpoints/best-model.ckpt"
