defaults:
  - model: transformer
  - data: fields
  - trainer: default
  - _self_

hydra:
  run:
    dir: ${paths.results}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# --- Global Project Configuration ---
project_name: "fields-transformer"
version: "1.0.0"
matmul_precision: "medium"

# --- Single Source of Truth: paths ---
paths:
  # absolute path for project root
  project_root: ${hydra:runtime.cwd}
  # root output directory for all runs
  results: "${paths.project_root}/results/transformer"
  nf_data: "${paths.project_root}/data/dataset_155.pt"
