defaults:
  - model: d2f
  - data: fields
  - trainer: default
  - _self_

hydra:
  run:
    dir: ${paths.results}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# --- Global Project Configuration ---
project_name: "d2f-transformer"
mode: train
mlflow_run_id: null
version: "1.0.0"
matmul_precision: "medium"

# --- Single Source of Truth: paths ---
paths:
  # absolute path for project root
  project_root: ${hydra:runtime.cwd}
  # root output directory for all runs
  results: "${paths.project_root}/results/transformer"
  nf_data: "${paths.project_root}/data/dataset_155.pt"
  ir_exp_data: "${paths.project_root}/data/smiles_ir/IR_v09_df_all_features.parquet"
  ir_sim_data: "${paths.project_root}/data/smiles_ir/IR_sim_data.parquet"
  smiles_vocab: "${paths.project_root}/data/smiles_ir/vocab.txt"
  ckpt: null #"${paths.results}/mlruns/168466128006132285/5ba73ea2848d4eb5b9e9cd29888acd60/artifacts/checkpoints/best-model.ckpt"
