defaults:
  - model: materials-model
  - data: materials
  - trainer: default
  - _self_

hydra:
  run:
    dir: ${paths.results}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# --- Global Project Configuration ---
project_name: "smiles-transformer"
mode: train
mlflow_run_id: null
version: "1.0.0"
matmul_precision: "medium"

# --- Single Source of Truth: paths ---
paths:
  # absolute path for project root
  project_root: ${hydra:runtime.cwd}
  # root output directory for all runs
  results: "${paths.project_root}/results/transformer"
  nf_data: "${paths.project_root}/data/dataset_155.pt"
  ir_data: "${paths.project_root}/data/smiles_ir/IR_v09_df_all_features.parquet" #"${paths.project_root}/data/smiles_ir/IR_sim_data.parquet"
  smiles_vocab: "${paths.project_root}/data/smiles_ir/vocab.txt"
  ckpt: null #"${paths.results}/mlruns/168466128006132285/304cbaa2342e4fc693ab4a183cfe6765/artifacts/checkpoints/best-model.ckpt"
